# this must come before the variables section,
# so variables specified there can override defaults specified in the template
include:
  - template: Dependency-Scanning.gitlab-ci.yml

# to make the previous template work with kanthaus-runner, which expects these tags
dependency_scanning:
  tags:
  - shared
  - linux

variables:
  # https://docs.docker.com/engine/userguide/storagedriver/selectadriver/
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/19971
  DOCKER_DRIVER: overlay


.defaults: &defaults
  tags:
  - shared
  - linux
  image: registry.gitlab.com/foodsharing-dev/images/ci:8.0.13


.ssh: &ssh
  before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEPLOY_SSH_KEY")
  - mkdir -p ~/.ssh
  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

.deploy: &deploy
  <<: *defaults
  # run it on our foodsharing ci server
  tags:
  - non-shared
  - foodsharing
  <<: *ssh
  stage: deploy
  dependencies:
  - build:frontend
  - build:backend
  - build:backend-websocket
  - build:docs
  script:
  - chmod -R 750 ./
  - (cd deployer && composer install)
  - deployer/vendor/bin/dep deploy $CI_ENVIRONMENT_NAME --revision $CI_COMMIT_SHA
  - ./scripts/deploy-websocket-restart
  - ./scripts/deploy-notify-slack

stages:
- outdated
- build
- test
- deploy

outdated:
  <<: *defaults
  stage: outdated
  script:
  # unfortunately "composer outdated -D" only works if you have installed the dependencies :/
  - composer install --verbose --prefer-dist --no-progress --no-interaction --classmap-authoritative --no-scripts --ignore-platform-reqs
  - ./scripts/ci-notify-outdated
  cache:
    key: outdated:v1
    paths:
    - vendor
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "outdated"
    when: always
  tags:
  # run on our server where we likely have the image already
  - non-shared
  - foodsharing

build:backend-websocket:
  <<: *defaults
  rules:
  - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'production'
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  interruptible: true
  image: node:16.13.2-alpine3.14
  stage: build
  script:
  - (cd websocket && yarn && yarn lint)
  cache:
    key: websocket:build:v2
    paths:
    - websocket/node_modules
  artifacts:
    expire_in: 1 week
    paths:
    - websocket/node_modules

build:frontend:
  <<: *defaults
  rules:
  - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'production'
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  interruptible: true
  image: node:16.13.2-alpine3.14
  stage: build
  script:
  - (cd client && yarn && yarn lint && yarn test && yarn build)
  cache:
    key: client:build:v2
    paths:
    - client/node_modules
  artifacts:
    expire_in: 1 week
    paths:
    - assets
    - sw.js

build:backend:
  <<: *defaults
  rules:
  - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'production'
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  interruptible: true
  image: registry.gitlab.com/foodsharing-dev/images/php:8.0.13
  stage: build
  script:
    - ./scripts/ci-backend-build
  cache:
    key: backend:build:v1
    paths:
    - vendor
    - .php-cs-fixer.php.cache
  artifacts:
    expire_in: 1 week
    paths:
    - assets
    - vendor

build:docs:
  <<: *defaults
  image:
    name: registry.gitlab.com/foodsharing-dev/images/mdbook_ci:1.1
  rules:
  - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'production'
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_INITDB_SKIP_TZINFO: 1
  services:
  # Note: Gitlab runner will mark a lot of service healthchecks as failed. This is a bug that will partly be addressed with the upcoming release of the gitlab-runner. It is also due to our configuration, e.g. the websocket container not exposing ports but listed as a service. Unfortunately, health check cannot be disabled.
    - name: registry.gitlab.com/foodsharing-dev/images/db/test:2
      alias: db
  stage: build
  script:
    - composer validate --no-check-all --no-check-publish
    - composer install --verbose --prefer-dist --no-progress --no-interaction --no-scripts --ignore-platform-reqs
    - ./scripts/ci-doc-build
  artifacts:
    expire_in: 1 week
    paths:
    - docs

test:backend:
  <<: *defaults
  interruptible: true
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_INITDB_SKIP_TZINFO: 1
    TZ: Europe/Berlin
    FF_NETWORK_PER_BUILD: 1
    REDIS_HOST: redis
    FS_ENV: test
  image: registry.gitlab.com/foodsharing-dev/images/php:8.0.13
  services:
# Note: Gitlab runner will mark a lot of service healthchecks as failed. This is a bug that will partly be addressed with the upcoming release of the gitlab-runner. It is also due to our configuration, e.g. the websocket container not exposing ports but listed as a service. Unfortunately, health check cannot be disabled.
    - name: redis:6.0.8-alpine
      alias: redis
    - name: registry.gitlab.com/foodsharing-dev/images/db/test:2
      alias: db
    - name: selenium/standalone-chrome:3.141.59-20200515
      alias: selenium
    - name: maildev/maildev
      alias: maildev
      command: ["bin/maildev",  "--web", "80", "--smtp", "25", "--hide-extensions", "STARTTLS"]
    - name: node:16.13.2-alpine3.14
      alias: websocket
      # websocket service runs with code that gets checked out later by the main build job. We use a file to synchronize that, so start websocket service only when that file has been recreated.
      command: ["/bin/sh", "-c", 'rm $CI_PROJECT_DIR/code_updated; while [ ! -e $CI_PROJECT_DIR/code_updated ]; do sleep 1; done; cd /builds/foodsharing-dev/foodsharing/websocket && yarn ts-node src/index.ts 0.0.0.0']
    - name: registry.gitlab.com/foodsharing-dev/images/web_ci:1.12
      alias: nginx
    - name: influxdb:1.8
      alias: influxdb

  # only run tests for MR, not for the target branch. While this might show to be dangerous, it also allows us to
  # deploy without relying on potentially flaky tests
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  dependencies:
    - build:frontend
    - build:backend
    - build:backend-websocket

  script:
    # Create file to notify websocket container that code is up to date
    - touch $CI_PROJECT_DIR/code_updated
    - ./scripts/ci-backend-test
  artifacts:
    expire_in: 1 month
    when: always
    paths:
    - tests/_output
    # make the report available in Gitlab UI. see https://docs.gitlab.com/ee/ci/unit_test_reports.html
    reports:
      junit: tests/_output/report-*.xml

test:backend-websocket:
  <<: *defaults
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'production'
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
  interruptible: true
  variables:
    REDIS_HOST: redis
  image: node:16.13.2-alpine3.14
  services:
    - name: redis:6.0.8-alpine
      alias: redis
  stage: test
  dependencies:
    - build:backend-websocket
  script:
    - (cd websocket && yarn test)
  cache:
    key: websocket:build:v2
    paths:
      - websocket/node_modules
  artifacts:
    expire_in: 1 week
    paths:
      - websocket/node_modules


deploy:beta:
  <<: *deploy
  environment:
    name: beta
    url: https://beta.foodsharing.de
  rules:
  - if: $CI_COMMIT_BRANCH == 'master'
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

deploy:production:
  <<: *deploy
  environment:
    name: production
    url: https://foodsharing.de
  rules:
  - if: $CI_COMMIT_BRANCH == 'production'
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

deploy:docs:
  <<: *defaults
  <<: *ssh
  stage: deploy
  dependencies:
  - build:docs
  script:
  - rsync -avz --delete docs/dist/ "deploy@devdocs.foodsharing.network:/var/www/devdocs/htdocs/"
  environment:
    name: docs
    url: https://devdocs.foodsharing.network
  rules:
  - if: $CI_COMMIT_BRANCH == 'master'
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
